name 'puppetlabs-cloudpack'
version '0.0.1'
source 'git://github.com/puppetlabs/puppet-cloudpack.git'
author 'puppetlabs'
license 'Apache Version 2.0'
summary 'Puppet Cloud Pack'
description 'Preview Faces extension for node bootstrapping in the cloud'
project_page 'https://projects.puppetlabs.com/projects/cloud-pack'
