name 'puppetlabs-cloud-provisioner'
version '1.0.0'
source 'git://github.com/puppetlabs/puppetlabs-cloud-provisioner.git'
author 'puppetlabs'
license 'Apache Version 2.0'
summary 'Puppet Cloud Provisioner'
description 'Faces application to launch and manage Amazon EC2 instances'
project_page 'https://projects.puppetlabs.com/projects/cloud-pack'
